repository: cmfcmf/modellbahn
baseurl: /modellbahn

title: Modellbahn
email: hallo@christianflach.de
description: Eine Sammlung von Hardware und Software, die ich auf meiner Modelleisenbahnanlage verwende.
twitter_username: christianmflach
github_username:  cmfcmf
lang: de_DE

markdown: kramdown
kramdown:
  input: GFM

theme: minima

plugins:
  - jekyll-sitemap

header_pages: [none] # cannot use an empty array here, because that is seen as not defined.

# https://github.com/benbalter/jekyll-titles-from-headings#configuration
titles_from_headings:
  enabled:     true
  strip_title: true

# https://github.com/jekyll/jekyll-sitemap#exclusions
defaults:
  -
    scope:
      path: "**/*.pdf"
    values:
      sitemap: false